### PR TITLE
Translation of "Install D locally" chapter

### PR DESCRIPTION
**Pull request by eresid**

### CODE REVIEW

**Comment by ikod** [comment]
Ok for me, will merge in few hours if no objection.

**Comment by wilzbach** [comment]
@ikod

> Ok for me, will merge in few hours if no objection.

While that's a very nice policy, I think only you two are currently working on this translation and watching it (the other watchers were automatically subscribed because they are admins too). So at least for now, I think you can merge directly ;-)
(in the worst case scenario it's a typo that can be easily fixed directly via the Github UI)

**Comment by ikod** [comment]
@wilzbach what is correct policy?

**Comment by wilzbach** [comment]
> @wilzbach what is correct policy?

Oh there's none. You are free to do (nearly) whatever you want.
I was just trying to say that atm you are only two persons, so unfortunately the someone to object which you are waiting for doesn't exist (I wasn't sure whether you were aware of that).

**Comment by ikod** [comment]
Thanks, got it!

**Pull request merged**
